services:
  - type: web
    name: limbus-draft
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
